import { Fragment } from 'react';

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '../../ui/dialog';
import type { FileData } from './DragAndDropContainer';
import EphemeralContent from './EphemeralContent';
import NonEphemeralContent from './NonEphemeralContent';

import type { EphemeralStatus } from '@/common/hooks/useEphemeral';
import { Invocation } from '@/common/types/invocation';
import type { NETWORK } from '@/common/types/soroban.enum';
import OverlayLoading from '@/common/views/OverlayLoading';
import { IWalletContent } from '@/modules/auth/interfaces/IAuthenticationContext';

interface UploadWasmDialogProps {
  open: boolean;
  onOpenChange: () => void;
  data: Invocation;
  wallet: IWalletContent | null;
  loading: boolean;
  files: FileData[];
  signedTransactionXDR: string | null;
  network: NETWORK;
  error: string | null;
  isLoading: boolean;
  status: EphemeralStatus | undefined;
  handleStart: ({ interval }: { interval: number }) => Promise<void>;
  handleStop: () => Promise<void>;
  uploadFiles: (f: FileData[]) => void;
  deleteFile: (indexFile: number) => void;
  handleButtonClick: () => void;
  resetState: () => void;
  isEphemeral: boolean;
  setIsEphemeral: React.Dispatch<React.SetStateAction<boolean>>;
}

function UploadWasmDialog({
  open,
  onOpenChange,
  data,
  wallet,
  loading,
  files,
  signedTransactionXDR,
  error,
  isLoading,
  status,
  handleStart,
  handleStop,
  uploadFiles,
  deleteFile,
  handleButtonClick,
  resetState,
  isEphemeral,
  setIsEphemeral,
}: Readonly<UploadWasmDialogProps>) {
  const loadingLocal = isLoading || loading;

  let buttonLabel = 'Load';
  if (!signedTransactionXDR && !wallet?.autoGenerated) {
    buttonLabel = 'Prepare';
  }

  return (
    <Fragment>
      {loadingLocal ? (
        <OverlayLoading />
      ) : (
        <Dialog
          open={open}
          onOpenChange={
            !isEphemeral
              ? onOpenChange
              : () => {
                  resetState();
                  handleStop();
                  onOpenChange();
                }
          }
        >
          <DialogContent
            data-test="import-account-modal-container"
            className="min-w-fit"
          >
            <DialogHeader>
              <DialogTitle
                data-test="import-account-modal-title"
                className="text-lg select-none"
              >
                {isEphemeral ? 'Ephemeral Network' : 'Upload Wasm File'}
              </DialogTitle>
              <DialogDescription
                data-test="import-account-modal-description"
                className="text-sm select-none"
              >
                {isEphemeral
                  ? 'You are using an ephemeral network. Ensure that your transactions can be completed without persistent state.'
                  : 'Please upload the WASM file of the contract'}
              </DialogDescription>
            </DialogHeader>
            {!isEphemeral ? (
              <NonEphemeralContent
                files={files}
                uploadFiles={uploadFiles}
                deleteFile={deleteFile}
                error={error}
                data={data}
                setIsEphemeral={setIsEphemeral}
                handleButtonClick={handleButtonClick}
                buttonLabel={buttonLabel}
                onOpenChange={onOpenChange}
              />
            ) : (
              <EphemeralContent
                files={files}
                uploadFiles={uploadFiles}
                deleteFile={deleteFile}
                error={error}
                status={status}
                handleStart={handleStart}
                handleStop={handleStop}
                isLoading={isLoading}
                handleButtonClick={handleButtonClick}
                buttonLabel={buttonLabel}
                setIsEphemeral={setIsEphemeral}
              />
            )}
          </DialogContent>
        </Dialog>
      )}
    </Fragment>
  );
}

export default UploadWasmDialog;
