name: CI

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
      - staging

env:
  PORT: 3000
  CYPRESS_HOST_PORT: 3001
  CYPRESS_BASE_URL_PREFIX: http://localhost:3000
  VITE_URL_API_BASE: http://localhost:3002/api

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Run test
        run: npm run test:ui
