name: Cypress Tests

on:
  pull_request:
    branches:
      - main

env:
  PORT: ${{ secrets.PORT }}
  CYPRESS_HOST_PORT: ${{ secrets.CYPRESS_HOST_PORT }}
  CYPRESS_BASE_URL_PREFIX: ${{ secrets.CYPRESS_BASE_URL_PREFIX }}
  VITE_AWS_COGNITO_REGION: ${{ secrets.VITE_AWS_COGNITO_REGION }}
  VITE_AWS_COGNITO_USER_POOL_ID: ${{ secrets.VITE_AWS_COGNITO_USER_POOL_ID }}
  VITE_AWS_COGNITO_CLIENT_ID: ${{ secrets.VITE_AWS_COGNITO_CLIENT_ID }}
  VITE_AWS_COGNITO_ENDPOINT: ${{ secrets.VITE_AWS_COGNITO_ENDPOINT }}
  VITE_AWS_COGNITO_E2E_USERNAME: ${{ secrets.VITE_AWS_COGNITO_E2E_USERNAME }}
  VITE_AWS_COGNITO_E2E_PASSWORD: ${{ secrets.VITE_AWS_COGNITO_E2E_PASSWORD }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          record: true
